//! Example JNI layer for `jnisafe-check`.
//!
//! One module per binding style, each mirroring the Java class of the same name
//! under `../java/example`. All four operate on the same `@Owned Box<String>`
//! handle so the differences are attributable to binding style, not domain:
//!
//! * [`hand_written`] / [`mangle`] — the **full** create/tryGet/get/set/drop
//!   contract, side by side: raw `Java_*` exports vs the `#[jni_mangle]`
//!   attribute. Diff the two to see exactly what the attribute does and nothing
//!   else.
//! * [`native_method`] — `native_method!`; can't name the `'local` lifetime of
//!   borrowed handles, so it covers only the owned-handle subset (create/drop).
//! * [`bind_type`] — `bind_java_type!`; the same owned subset **plus** the
//!   Rust→Java call direction (methods/fields/constructors).
//! * [`overloaded`] — two same-named natives resolving to the long mangled form.
//! * [`document`] — the same handle stored in a Java *field* across calls rather
//!   than passed per-call: the `Document` class extends the `NativeObject` base
//!   class so the field is guarded by a read/write lock, and the natives are the
//!   ordinary parameter path (`@Ref`/`@Mut`/`@Owned`).
//!
//! Built as a `cdylib`, this is also a runnable native library: `example.Main`
//! (`System.loadLibrary("example")`) exercises every class. `hand_written`,
//! `mangle`, and `bind_type`'s natives auto-bind via their exported `Java_*`
//! symbols; the `native_method!` tables are registered from [`JNI_OnLoad`].

use std::ffi::c_void;

use jni::{JavaVM, jni_str, sys};

pub mod bind_type;
pub mod document;
pub mod hand_written;
pub mod mangle;
pub mod native_method;
pub mod overloaded;

/// Registers the `native_method!` tables that the JVM can't auto-bind, because
/// (unlike the hand-written, `#[jni_mangle]`, and `bind_java_type!` natives)
/// they export no `Java_*` symbol — they're built for `RegisterNatives`.
///
/// Called by the JVM when `System.loadLibrary("example")` loads this cdylib.
///
/// # Safety
///
/// `unsafe` because the JVM-dictated `JNI_OnLoad` signature takes a raw
/// `*mut JavaVM` that this function dereferences. The JVM only ever calls it
/// with the live `JavaVM` pointer for the loading VM, which satisfies the
/// contract; it must not be called by hand with anything else.
#[unsafe(no_mangle)]
pub unsafe extern "system" fn JNI_OnLoad(
    vm: *mut sys::JavaVM,
    _reserved: *mut c_void,
) -> sys::jint {
    // SAFETY: `vm` is the live `JavaVM` the JVM hands to `JNI_OnLoad`.
    let vm = unsafe { JavaVM::from_raw(vm) };
    let registered = vm.attach_current_thread(|env| -> jni::errors::Result<()> {
        // SAFETY: each table's name/signature/fn-pointer triple is generated by
        // `native_method!` from the Rust impl, and jnisafe-check verifies it
        // against the Java declarations at build time.
        let class = env.find_class(jni_str!("example/NativeMethod"))?;
        unsafe { env.register_native_methods(class, native_method::METHODS)? };

        let class = env.find_class(jni_str!("example/Overloaded"))?;
        unsafe { env.register_native_methods(class, overloaded::METHODS)? };
        Ok(())
    });
    match registered {
        Ok(()) => sys::JNI_VERSION_1_6,
        // Returning an unsupported version makes the JVM fail the load loudly.
        Err(_) => 0,
    }
}
